# -*- coding: utf-8 -*-
"""EDA_COVID19_Correto_Obede.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14Oh90AYqjd1JHQi5aE9yi83Mc63LI5Vy

#  Análise Exploratória Profunda da COVID-19 no Brasil
Este projeto realiza uma Análise Exploratória Profunda dos dados da COVID-19 no Brasil, com foco em estatísticas, tendências, visualizações interativas e insights.

**Autor:** Obede Vieira dos Santos
www.linkedin.com/in/obede-vieira-dos-santos-981303324
"""

#  Importando bibliotecas
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px
import warnings
warnings.filterwarnings('ignore')
sns.set(style='whitegrid')
plt.rcParams['figure.figsize'] = (14, 6)

#  Carregando os dados da fonte correta
url = 'https://raw.githubusercontent.com/wcota/covid19br/master/cases-brazil-states.csv'
df = pd.read_csv(url, parse_dates=['date'])
df.head()

#  Limpeza dos dados
df = df[(df['newCases'] >= 0) & (df['newDeaths'] >= 0)]
df.dropna(inplace=True)
df.reset_index(drop=True, inplace=True)

"""##  Análise Descritiva"""

df.info()

df.describe()

sns.heatmap(df.isnull(), cbar=False, cmap='viridis')
plt.title('Mapa de Calor dos Valores Ausentes')
plt.show()

df[['newCases', 'newDeaths']].hist(bins=30, figsize=(12,5))
plt.suptitle('Distribuição de Novos Casos e Mortes')
plt.show()

print('Média de novos casos:', df['newCases'].mean())
print('Mediana:', df['newCases'].median())
print('Desvio padrão:', df['newCases'].std())

sns.boxplot(x=df['newCases'])
plt.title('Boxplot de Novos Casos')
plt.show()

"""##  Análise Temporal Nacional"""

brasil = df.groupby('date')[['newCases', 'newDeaths']].sum().reset_index()
sns.lineplot(data=brasil, x='date', y='newCases', label='Novos Casos')
sns.lineplot(data=brasil, x='date', y='newDeaths', label='Novas Mortes')
plt.title('Evolução de Casos e Mortes no Brasil')
plt.show()

"""##  Análise Temporal por Estado (Top 5)"""

top5 = df[df['date'] == df['date'].max()].nlargest(5, 'totalCases')['state']
df_top = df[df['state'].isin(top5)]
sns.lineplot(data=df_top, x='date', y='newCases', hue='state')
plt.title('Evolução dos Novos Casos - Top 5 Estados')
plt.show()

"""## Correlação entre Variáveis"""

sns.heatmap(df.corr(numeric_only=True), annot=True, cmap='coolwarm')
plt.title('Correlação entre Variáveis')
plt.show()

"""##  Visualização Interativa"""

fig = px.scatter(latest, x='totalCases', y='deaths', color='state',
                 hover_name='state',
                 title='Casos x Mortes por Estado')
fig.show()

"""##  Conclusão

- A pandemia teve diferentes impactos nos estados brasileiros.
- O volume de casos e mortes tem forte correlação.
- Algumas regiões exigiram atenção especial pelas autoridades.
- Esse projeto pode ser expandido com previsão de casos ou análises geoespaciais.
"""